baseURL = "https://wesleystoolbox.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "wesleystoolbox"
title = "Wesley's Toolbox"
[markup.goldmark.renderer]
unsafe = true
