

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 4



# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_left]]
name = "Quick Start"
url = "#"

[[footer_left]]


# footer menu middle
#[[footer_middle]]


# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"

[[footer_right]]
name = "FAQ"
url = "faq/"